---
title: "Areas of Seabed depths in MEASO and CCAMLR ASD areas"
author: "Andrew Constable"
date: "31/08/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r echo=FALSE}
# Seabed_file<-"C:\\_w\\_d\\Catch\\etopo2_ccamlr_measo\\etopo2_ccammlr_measo.rds"

Seabed_file<-"C:\\_w\\_d\\seabed GEBCO\\gebco_cells_2000m.rds"
Seabed_areas <- readRDS(Seabed_file)
cat("File with Seabed area data: ",Seabed_file,"\n",sep="")
cat("Variable names in seabed area file:",names(Seabed_areas),"\n",sep="  ")

# give each cell an area of 2x2 km until it is available in input file
Seabed_areas<-cbind(Seabed_areas,rep(4,nrow(Seabed_areas)))

# rename variables to be consistent with code - check order is correct

names(Seabed_areas)<-c("Lon","Lat","Cell","Depth","Iceshelf","MEASO","ASD","Area")
cat("Variable names in seabed area file:",names(Seabed_areas),"\n",sep="  ")


Cbed<-Seabed_areas[!(Seabed_areas[,"Iceshelf"]),c("Lon","Lat","Depth","MEASO","ASD","Area")]

# make NA for CCAMLR or MEASO areas into "Outside"
Cbed[is.na(Cbed[,"ASD"]),"ASD"]<-"Outside"
Cbed[is.na(Cbed[,"MEASO"]),"MEASO"]<-"Outside"

ASD<-sort(unique(Cbed[,"ASD"]))
MEASOarea<-sort(unique(Cbed[,"MEASO"]))




# seabed areas from CCAMLR Statistical Bulletin (CSB - converted to square nautical miles i.e. multiply by 1/1.852^2 [= 3.429904])
conversion<-1 # 1/1.852^2 

# 0-600 m depth
m0_600<-c(219745, 37431, 46435, 2254, 526672, 50766, 367887, 210302, 0, 399, 10374, 144396, 58399, 17534, 5414, 342091, 267789, 302111)*conversion

# 600-1800 m depth
m600_1800<-c(84150, 73651, 67656, 25691, 150069, 89261, 177191, 98452, 20051, 129167, 23164, 130830, 118238, 43102, 30975, 243829, 118972, 115677)*conversion

# deeper than 1800 m depth
m1800plus<-c(318526, 745076, 915246, 916662, 1416504, 6134892, 4021956, 1189462, 485484, 550334, 2462471, 806884, 466281, 608828, 549379, 2111495, 4350752, 1766153)*conversion
 
# total seabed area
mTotal<-c(622421, 856158, 1029337, 944607, 2093245, 6274919, 4567034, 1498216, 505535, 679900, 2496009, 1082110, 642918, 669464, 585768, 2697415, 4737513, 2183941)*conversion

CSB_Cbed_nm<-data.frame(ASD[ASD!="Outside"],m0_600,m600_1800,m1800plus,mTotal)


Depth_intervals<-c(0,-300, -600, -900, -1200, -1800,-10000)


fnDepthArea<-function(dInt          # which depth interval
                     ,Depth_ints   # vector of depth intervals
                     ,Cb_dat         # dataframe with "Depth", "Area" 
                                   #  optional for none, one or both of "MEASO", "ASD"
                     ){
# find grouping variables (if any)
  Groups<-dimnames(Cb_dat)[[2]] 
  Groups<-Groups[which(Groups %in% c("MEASO","ASD"))]
# subset data from depth range
    x<- Cb_dat[(Cb_dat[,"Depth"] <   Depth_ints[dInt] & 
                Cb_dat[,"Depth"] >=  Depth_ints[(dInt+1)]),]

  if(length(Groups)>0) {
           GroupBy<-lapply(Groups,function(grp,x1){return(x1[,grp])},x)
           res <- aggregate(x[,"Area"],GroupBy,sum)
         
           names(res)<-c(Groups,"Area")
            res<-cbind(res[,Groups],rep(Depth_ints[dInt],nrow(res)),res[,"Area"])
           names(res)<-c(Groups,"Depth","Area")
           return(res)
       } else {
           sumx<-matrix(c(Depth_ints[dInt], sum(x[,"Area"])),nrow=1)
           dimnames(sumx)[[2]]<-c("Depth","Area")
           return(sumx) 
       } # end else
     } # end fnDepthArea



Result<-do.call(rbind,lapply(seq(1:(length(Depth_intervals)-1)),fnDepthArea,Depth_intervals,Cbed))


# now check against CCAMLR seabed areas

Result[Result[,"Depth"]>(-600),"CCAMLRstrata"]<-1
Result[Result[,"Depth"]>(-1800) & Result[,"Depth"]<=(-600),"CCAMLRstrata"]<-2

res<-aggregate(Result[,"Area"],list(Result[,"ASD"],Result[,"CCAMLRstrata"]),sum)
names(res)<-c("ASD","CCAMLRstrata","Area")

ResMergeDepths<-merge(res[res[,"CCAMLRstrata"]==1,c("ASD","Area")],res[res[,"CCAMLRstrata"]==2,c("ASD","Area")],by="ASD",all=TRUE)
ResMergeDepths[is.na(ResMergeDepths)]<-0
ResMergeDepths<-ResMergeDepths[ResMergeDepths[,"ASD"]!="Outside",]

names(ResMergeDepths)<-c("ASD","e0_600","e600_1800")

x<-CSB_Cbed_nm[,c("m0_600","m600_1800")]
y<-ResMergeDepths[,c("e0_600","e600_1800")]

Cbed_compare<-cbind(ResMergeDepths[,"ASD"]
                  ,round((x-y)/x,2)
                  ) # end cbind
  
cat("Compare depth zone 0-600m (CCAMLR-etopo2")
print(Cbed_compare)

# save areas

```
```{r echo=FALSE}
# MEASO Areas from main document
MEASOareas<-matrix(c("AOA","Atlantic Ocean","Antarctic","48"
                    ,"AOS","Atlantic Ocean","Subantarctic","48"
                    ,"AON","Atlantic Ocean","Northern","48"
                    ,"CIA","Central Indian","Antarctic","58"
                    ,"CIS","Central Indian","Subantarctic","58" 
                    ,"CIN","Central Indian","Northern","58"
                    ,"EIA","East Indian   ","Antarctic","58"
                    ,"EIS","East Indian   ","Subantarctic","Outside"
                    ,"EIN","East Indian   ","Northern","Outside"
                    ,"EPA","East Pacific  ","Antarctic","48"
                    ,"EPS","East Pacific  ","Subantarctic","48"
                    ,"EPN","East Pacific  ","Northern","Outside"
                    ,"WPA","West Pacific  ","Antarctic","88"
                    ,"WPS","West Pacific  ","Subantarctic","Outside"
                    ,"WPN","West Pacific  ","Northern","Outside"
                    ,"Outside","not in MEASO area","",""),byrow=TRUE,ncol=4)
dimnames(MEASOareas)[[2]]<-c("Code","Sector","Zone","CSB_Stat_Area")


# create matrix of proportions of a depth stratum in a subarea (columns) to be allocated to MEASO areas (rows)

# generate list of (ASD,depth_stratum) vectors
ASD_depth_categories<-unique(Result[,c("ASD","Depth")])

fnPropInMarea<-function(i,ASD_depth,cbed_areas,M_areas){
     res<-rep(0,length(M_areas))
     x<-cbed_areas[cbed_areas[,"ASD"]  ==ASD_depth[i,"ASD"] & 
                   cbed_areas[,"Depth"]==ASD_depth[i,"Depth"], c("MEASO","Area")]
     x[,"prop"]<-x[,"Area"]/sum(x[,"Area"])
     res[match(x[,"MEASO"],M_areas)]<-round(x[,"prop"],3)
     return(c(ASD_depth[i,],res))
     } # end fnPropInMarea

# for each ASD,depthStratum combination, determine proportions across MEASO areas
ASD_depth_propInMEASOareas<-do.call(rbind,lapply(c(1:nrow(ASD_depth_categories)),fnPropInMarea,ASD_depth_categories,Result,MEASOareas[,"Code"]))

saveRDS(ASD_depth_propInMEASOareas,file="ASD_depth_propInMEASOareas.rds")


```
